force-app/main/default/objects/Assignment__c/fields/AssignmentGroup__c.field-meta.xml
<CustomField>
    <fullName>AssignmentGroup__c</fullName>
    <label>AssignmentGroup</label>
    <referenceTo>AssignmentGroup__c</referenceTo>
    <relationshipLabel>Assignments</relationshipLabel>
    <relationshipName>Assignments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Assignment__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>DueDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AssignmentGroup__c/AssignmentGroup__c.object-meta.xml
<CustomObject>
    <label>AssignmentGroup</label>
    <nameField>
        <label>Group Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AssignmentGroups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AssignmentGroup__c/fields/GroupDescription__c.field-meta.xml
<CustomField>
    <fullName>GroupDescription__c</fullName>
    <label>GroupDescription</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AssignmentController.cls
public class AssignmentController {
    
    @AuraEnabled(cacheable=true)
    public static List<AssignmentGroup__c> getGroupAndAssignments() {
        return [
            select id,name,GroupDescription__c,(select id,Title__c,Description__c, 
            DueDate__c, Priority__c, Status__c from Assignments__r) 
            from AssignmentGroup__c  
        ];
    }

    @AuraEnabled(cacheable=true)
    public static List<Assignment__c> getAssignmentList(){
        List<Assignment__c> assignmentList = new List<Assignment__c>();
        try {    
            assignmentList = [select Id, Name,  Title__c, Description__c, DueDate__c, Status__c, Priority__c, AssignmentGroup__c 
            from Assignment__c order by DueDate__c];
        } catch (Exception ex) {
            throw new AuraHandledException('Error '+ex.getMessage());
        }
        return assignmentList;
    }

}